export const telephonePrefixes = [
  { name: 'Argentina', code: '+54', flag: 'ar' },
  { name: 'Australia', code: '+61', flag: 'au' },
  { name: 'Austria', code: '+43', flag: 'at' },
  { name: 'Belgium', code: '+32', flag: 'be' },
  { name: 'Bolivia', code: '+591', flag: 'bo' },
  { name: 'Brazil', code: '+55', flag: 'br' },
  { name: 'Canada', code: '+1', flag: 'ca' },
  { name: 'Chile', code: '+56', flag: 'cl' },
  { name: 'Colombia', code: '+57', flag: 'co' },
  { name: 'Costa Rica', code: '+506', flag: 'cr' },
  { name: 'Cuba', code: '+53', flag: 'cu' },
  { name: 'Denmark', code: '+45', flag: 'dk' },
  { name: 'Dominican Republic', code: '+1-809, +1-829, +1-849', flag: 'do' },
  { name: 'Ecuador', code: '+593', flag: 'ec' },
  { name: 'El Salvador', code: '+503', flag: 'sv' },
  { name: 'Finland', code: '+358', flag: 'fi' },
  { name: 'France', code: '+33', flag: 'fr' },
  { name: 'Germany', code: '+49', flag: 'de' },
  { name: 'Greece', code: '+30', flag: 'gr' },
  { name: 'Guatemala', code: '+502', flag: 'gt' },
  { name: 'Honduras', code: '+504', flag: 'hn' },
  { name: 'Iceland', code: '+354', flag: 'is' },
  { name: 'Ireland', code: '+353', flag: 'ie' },
  { name: 'Italy', code: '+39', flag: 'it' },
  { name: 'Jamaica', code: '+1-876', flag: 'jm' },
  { name: 'Luxembourg', code: '+352', flag: 'lu' },
  { name: 'Mexico', code: '+52', flag: 'mx' },
  { name: 'Netherlands', code: '+31', flag: 'nl' },
  { name: 'New Zealand', code: '+64', flag: 'nz' },
  { name: 'Nicaragua', code: '+505', flag: 'ni' },
  { name: 'Norway', code: '+47', flag: 'no' },
  { name: 'Panama', code: '+507', flag: 'pa' },
  { name: 'Paraguay', code: '+595', flag: 'py' },
  { name: 'Peru', code: '+51', flag: 'pe' },
  { name: 'Poland', code: '+48', flag: 'pl' },
  { name: 'Portugal', code: '+351', flag: 'pt' },
  { name: 'Puerto Rico', code: '+1-787, +1-939', flag: 'pr' },
  { name: 'Spain', code: '+34', flag: 'es' },
  { name: 'Sweden', code: '+46', flag: 'se' },
  { name: 'Switzerland', code: '+41', flag: 'ch' },
  { name: 'Trinidad and Tobago', code: '+1-868', flag: 'tt' },
  { name: 'United Kingdom', code: '+44', flag: 'gb' },
  { name: 'United States', code: '+1', flag: 'us' },
  { name: 'Uruguay', code: '+598', flag: 'uy' },
  { name: 'Venezuela', code: '+58', flag: 've' },
  { name: 'Russia', code: '+7', flag: 'ru' },
  { name: 'Turkey', code: '+90', flag: 'tr' },
  { name: 'Ukraine', code: '+380', flag: 'ua' },
  { name: 'Israel', code: '+972', flag: 'il' }
];
